
{
  foreach (var r in DataModel.GetRecords().Where(_ =&gt; ～)) 
  {
    var id = r.ID;
    var result = await Task&lt;int&gt;.Run(() =&gt; 
    {
    }).ConfigureAwait(false);
    r.Realm.Write(() =&gt; { r.col = result; });

例外がスローされました: 'System.Exception' (Realm.dll の中)
型 'System.Exception' の例外が Realm.dll で発生しましたが、ユーザー コード内ではハンドルされませんでした
Realm accessed from incorrect thread.

