
{
  foreach (var r in DataModel.GetRecords().Where(_ =&gt; ～)) 
  {
    await Task.Run(() =&gt; 
    {
      var id = r.ID;

例外がスローされました: 'System.Exception' (Realm.dll の中)
型 'System.Exception' の例外が Realm.dll で発生しましたが、ユーザー コード内ではハンドルされませんでした
Realm accessed from incorrect thread.


