
void Start () {
    Debug.Log ("start");
    TestAsync (1);
    TestAsync (2);
    Debug.Log ("done");
}

async void TestAsync (int number) {
    var task = Task.Run (async () =&gt; await Test2Async (number));
    await task;
}

async Task Test2Async (int number) {
    Debug.Log ($"begin task {number}");
    await Task.Delay (1000); // 1秒待機
    throw new Exception (); // 例外発生
    Debug.Log ($"end task {number}");
}

