
public class UserService
{
    public string GetUserName(int userId)
    {
        var dataAccessor = new UserDataAccessor();

        try
        {
            var user = dataAccessor.Find(userId);
            return user.Name;
        }
        catch(Exception ex)
        {
            // InnerExceptionに実際に起きた例外を入れてあげる
            throw new ServiceException($"ユーザ名の取得に失敗しました。 ユーザID:{userId}", ex);
        }
    }
}

