

        public class MyException : Exception {}

        public class MyClass {
            public static void TestTargetFunc() { throw new MyException(); }
        }

        [TestCase]
        public void TestThrows()
        {
            // Test OK.
            Assert.Throws&lt;MyException&gt;(() =&gt; MyClass.TestTargetFunc());
            // Test NG.
            Assert.Throws&lt;Exception&gt;(() =&gt; MyClass.TestTargetFunc());
        }

        [TestCase]
        public void TestCatch()
        {
            // Test OK.
            Assert.Catch&lt;MyException&gt;(() =&gt; MyClass.TestTargetFunc());
            // Test OK.
            Assert.Catch&lt;Exception&gt;(() =&gt; MyClass.TestTargetFunc());
        }


