try {

 } 
catch (Exception ex)
{ 
    return; 
}

