More than 1 year has passed since last update.まず普通に再帰関数を書きます。n が 100000 以上になるまで +1 し続ける関数です。しかし結果はこうなります。Recurse メソッドが終了する前に次の Recurse メソッドを再帰呼び出しするため、引数などが解放される前にスタックに積まれていきます。その結果、必要なスタックがあらかじめ割り当てられたサイズを超えてしまい、このエラーが発生します。これを Task を用いて書き直すと次のようになります。結果は次のように正常に終了します。メソッド Recurse は呼び出した Recurse の終了を待ちません。そのため引数などは逐次解放されます。返された Task は合成され、Result プロパティで戻り値を取得できます。


