
public class TestClass
{
  static double div(int a, int b)
  {
    try
    {
      return a / b;
    }
    catch (DivideByZeroException　e)
    {
      System.Console.WriteLine("divでcatch: " + e.Message + ", " + e.TargetSite);
      throw;
    }
  }

  public static void Main()
  {
    try
    {
      double x = div(1, 0);
    }
    catch (DivideByZeroException e)
    {
      System.Console.WriteLine("Mainでcatch: " + e.Message + ", " + e.TargetSite);
    }
  }
}

