
try
{
}
catch (Exception ex)
{
    logger.Error(ex, "Something bad happened");
}

