
catch(FileNotFoundException ex){//存在しないファイル}
catch(NullReferenceException ex){//nullのオブジェクトを操作した}
catch(DivideByZeroException ex){//0による除算}
catch(IndexOutOfRangeException ex){//配列境界こえた}
catch(Exception ex){//その他の例外}

{Console.WriteLine(ex.Message);}//例外に関するメッセージ
{Console.WriteLine(ex.Source);}//発生源のアプリやファイル名
{Console.WriteLine(ex.HelpLink);}//その例外に関するヘルプリンク
{Console.WriteLine(ex.StackTrace);}//処理メソッド説明(デバッグ情報でスタックトレース(スタックの追跡))
{Console.WriteLine(ex.TargetSite);}//例外発生した部分表示

//1つの処理で複数例外でる場合、throwで別のメソッドに再スローすればいい
//逆に複数処理で1つの例外でる場合、whenでまとめればいい

