
private async void Button_Click_4(object sender, RoutedEventArgs e)
{
    var t1 = Task.Run(() =&gt; { throw new NotImplementedException(); });
    var t2 = Task.Run(() =&gt; { throw new ArgumentException(); });
    var t3 = Task.Run(() =&gt; { throw new InvalidOperationException(); });
    var all = Task.WhenAll(t1, t2, t3);

    try
    {
        // WhenAllのタスクのローカル変数を作って、それをtry catchする
        await all;
    }
    catch (Exception ex)
    {
        // ex には例外のうちの1つしか入ってないので、
        // WhenAllのタスクのローカル変数のExceptionプロパティ
        // (それがAggregateExceptionになってる)を見て
        // すべての例外を取り出す
        if (all.Exception is AggregateException age)
        {
            age.InnerExceptions.ToList().ForEach((ages) =&gt; Debug.WriteLine(ages.GetType()));
        }
    }
}

